# version: '3.8'
# services:
#   service_api_shopee:
#     container_name: service_api_shopee
#     restart: always
#     build:
#       context: ./
#       dockerfile: ./dockerfile
#     ports:
#       - 3100:3100
#     environment:
#       - TZ=Asia/Bangkok
#     networks:
#       - eiei
#     command: >
#       bash -c "
#         npm install &&
#         npm run dev"
#   postgreSQL:
#     container_name: pg_container
#     image: postgres
#     restart: always
#     volumes:
#       # - ./db:/db
#       - ./db/:/var/lib/postgresql
#       - ./db/data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: test_db
#     networks:
#       - eiei
#     ports:
#       - "5432:5432"
#   pgadmin:
#     container_name: pgadmin4_container
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - "5050:80"
#     networks:
#       - eiei
# networks:
#   eiei:
#     name: eiei
    
version: '3.8'

services:
  service_api_shopee:
    container_name: service_api_shopee
    restart: always
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - 3100:3100
    environment:
      - TZ=Asia/Bangkok
    networks:
      - eiei
    command: >
      bash -c "
        npm install &&
        npm run dev"

  postgreSQL:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      eiei:
        ipv4_address: 172.20.0.4 # Specify the desired static IP address
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - eiei

networks:
  eiei:
    name: eiei
    ipam:
      config:
        - subnet: 172.20.0.0/16 # Define a subnet for the custom network
